apiVersion: apps/v1
kind: Deployment
metadata:
  name: kom-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kom-operator
  template:
    metadata:
      labels:
        name: kom-operator
    spec:
      serviceAccountName: kom-operator
      containers:
        - name: kom-operator
          # Replace this with the built image name
          image: kaiso/kom-operator:v0.1.1
          command:
          - kom-operator
          # imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kom-operator"
