apiVersion: apps/v1
kind: Deployment
metadata:
  name: kom-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kom-operator
  template:
    metadata:
      labels:
        name: kom-operator
    spec:
      serviceAccountName: kom-operator
      containers:
        - name: kom-operator
          # Replace this with the built image name
          image: kaiso/kom-operator:v1.0.2
          command:
          - kom-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kom-operator"
            - name: SMART_RELOAD
              value: "false"
