{{ if .Values.rbac.create }}

# roles bindings

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kaiso:kom-operator
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kom-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kom-operator
  apiGroup: rbac.authorization.k8s.io


# end of role bindings


{{ end }}