{{ if .Values.rbac.create }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kom-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kom-operator
subjects:
- kind: ServiceAccount
  name: kom-operator
  namespace: "{{.Values.namespace.name }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kom-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kom-proxy-role
subjects:
- kind: ServiceAccount
  name: kom-operator
  namespace: "{{.Values.namespace.name }}"

{{ end }}