apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 01825d50.kaiso.github.io
kind: ConfigMap
metadata:
  name: kom-manager-config
  namespace: "{{.Values.namespace.name }}"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    provider: kaiso
    version: "{{.Chart.AppVersion }}"
  name: kom-controller-manager-metrics-service
  namespace: "{{.Values.namespace.name }}"
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    provider: kaiso
    version: "{{.Chart.AppVersion }}"
  name: kom-operator
  namespace: "{{.Values.namespace.name }}"
spec:
  replicas: {{.Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: SMART_RELOAD
          value: "false"
        - name: WATCH_NAMESPACE
          value: "{{ .Values.watchNamespace }}"
        - name: LOADBALANCER_PUBLISHED_SERVICE
          value: "{{ .Values.loadbalancer.publishedService }}"
        - name: LOADBALANCER_REPLICA_COUNT
          value: "{{ .Values.loadbalancer.replicaCount }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: "kaiso/kom-operator:{{.Chart.AppVersion }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kom-operator
      terminationGracePeriodSeconds: 10

          