{{ if .Values.rbac.create }}
# roles bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kom-leader-election-rolebinding
  namespace: "{{.Values.namespace.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kom-leader-election-role
subjects:
- kind: ServiceAccount
  name: kom-operator
  namespace: "{{.Values.namespace.name }}"
# end of role bindings
{{ end }}