{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{.Values.namespace.name }}"
  name: kom-operator
  labels:
    provider: kaiso
    version: "{{.Chart.AppVersion }}"
{{ end }}